import {  Pacifico , JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";


const JetBrainsMono = JetBrains_Mono({
  variable: "--font-JetBrains_Mono",
  weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" ,"800"],
  subsets: ["latin"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: ["400"],
  subsets: ["latin"],
});



export const metadata = {
  title: "SilverSv",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainsMono.variable}  ${pacifico.variable} antialiased`}
      >
        <Header/>
        <StairTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
